# Generated by Django 2.1.5 on 2019-02-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_auto_20190127_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('short_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='abbreviazione')),
            ],
            options={
                'verbose_name': 'tipo analisi',
                'verbose_name_plural': 'tipi analisi',
            },
        ),
    ]
