# Generated by Django 2.1.5 on 2019-02-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_auto_20190215_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.AnalysisName', verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_place',
            field=models.CharField(default='', max_length=100, verbose_name='luogo di nascita'),
            preserve_default=False,
        ),
    ]
