# Generated by Django 2.1.5 on 2019-02-17 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_auto_20190215_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='data')),
                ('name', models.CharField(default='MOC', max_length=3, verbose_name='moc')),
                ('ls_t', models.FloatField(blank=True, null=True, verbose_name='LS T-score')),
                ('ls_z', models.FloatField(blank=True, null=True, verbose_name='LS Z-score')),
                ('ls_bmd', models.FloatField(blank=True, null=True, verbose_name='LS BMD')),
                ('fn_t', models.FloatField(blank=True, null=True, verbose_name='FN T-score')),
                ('fn_z', models.FloatField(blank=True, null=True, verbose_name='FN Z-score')),
                ('fn_bmd', models.FloatField(blank=True, null=True, verbose_name='FN BMD')),
                ('ft_t', models.FloatField(blank=True, null=True, verbose_name='FT T-score')),
                ('ft_z', models.FloatField(blank=True, null=True, verbose_name='FT Z-score')),
                ('ft_bmd', models.FloatField(blank=True, null=True, verbose_name='FT BMD')),
            ],
            options={
                'verbose_name': 'MOC',
                'verbose_name_plural': 'MOC',
            },
        ),
    ]
