# Generated by Django 2.1.5 on 2019-02-18 09:51

from django.db import migrations, models
import patients.tools


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_auto_20190217_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', patients.tools.ItalianPeriodDateField(verbose_name='data')),
            ],
        ),
    ]
