# Generated by Django 2.1.5 on 2019-02-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
